package com.revature.main;

import org.hibernate.Session;
import org.hibernate.Transaction;

import com.revature.beans.Account;
import com.revature.beans.Answer;
import com.revature.beans.Library;
import com.revature.beans.Question;
import com.revature.beans.Status;
import com.revature.util.HibernateUtil;

public class Driver {

	public static void main(String[] args) {
		init();
	}

	public static void init() {

		Session s = HibernateUtil.getSession();
		System.out.println(s.isOpen());
		Transaction tx = s.getTransaction();
		tx.begin();
		
		Account acc = new Account();
		acc.setAdmin(true);
		acc.setEmail("collinmeaney375@gmail.com");
		acc.setUsername("cmeaney");
		acc.setPassword("password4");
		s.save(acc);
		
		Library lib1 = new Library();
		lib1.setName("Angular");
		lib1.setStatus(Status.PUBLIC);
		lib1.setAccount(acc);
		s.save(lib1);
		
		Question q1 = new Question();
		q1.setLibrary(lib1);
		q1.setDifficulty(1);
		q1.setValue("ngFor is used to toggle display of an element.");
		Question q2 = new Question();
		q2.setLibrary(lib1);
		q2.setDifficulty(1);
		q2.setValue("True or False. ngIf does NOT remove the element from the DOM if the expression evaluates to false.");
		Question q3 = new Question();
		q3.setLibrary(lib1);
		q3.setDifficulty(1);
		q3.setValue("Which of the following are attribute directives? (Choose all that apply)");
		Question q4 = new Question();
		q4.setLibrary(lib1);
		q4.setDifficulty(1);
		q4.setValue("True or False. ngClass is used to add/remove multiple styles using key/value pairs of CSS");
		Question q5 = new Question();
		q5.setLibrary(lib1);
		q5.setDifficulty(1);
		q5.setValue("True or False. ngStyle is used to manipulate multiple CSS classes.");
		Question q6 = new Question();
		q6.setLibrary(lib1);
		q6.setDifficulty(1);
		q6.setValue("True or False. All applications have at least one component, the root component.");
		Question q7 = new Question();
		q7.setLibrary(lib1);
		q7.setDifficulty(1);
		q7.setValue("Which of the following lib1raries defines the @Component decorator? (Choose the best option)");
		Question q8 = new Question();
		q8.setLibrary(lib1);
		q8.setDifficulty(1);
		q8.setValue("Which of the following metadata specifies the path to the file that defines the HTML to output?");
		Question q9 = new Question();
		q9.setLibrary(lib1);
		q9.setDifficulty(1);
		q9.setValue("Which of the following are valid properties of @NgModule?");
		Question q10 = new Question();
		q10.setLibrary(lib1);
		q10.setDifficulty(1);
		q10.setValue("Which of the following are NOT permitted within Angular 2 Templates: (Choose all that apply)");
		Question q11 = new Question();
		q11.setLibrary(lib1);
		q11.setDifficulty(1);
		q11.setValue("Which @NgModule property specifies services that are used throughout the application? (Choose the best option)");
		Question q12 = new Question();
		q12.setLibrary(lib1);
		q12.setDifficulty(1);
		q12.setValue("Which of the following metadata properties specifies the CSS selector to which the component will match?");
		Question q13 = new Question();
		q13.setLibrary(lib1);
		q13.setDifficulty(1);
		q13.setValue("Which @NgModule property specifies services that are used throughout the application? (Choose the best option)");
		Question q14 = new Question();
		q14.setLibrary(lib1);
		q14.setDifficulty(1);
		q14.setValue("Which of the following snippets correctly identifies a class as a service that you want injected in another class? (Choose the best option)");
		Question q15 = new Question();
		q15.setLibrary(lib1);
		q15.setDifficulty(1);
		q15.setValue("True or False. ngClass is used to add/remove multiple styles using key/value pairs of CSS");
		Question q16 = new Question();
		q16.setLibrary(lib1);
		q16.setDifficulty(1);
		q16.setValue("True or False. ngFor is used to toggle display of an element.");
		Question q17 = new Question();
		q17.setLibrary(lib1);
		q17.setDifficulty(1);
		q17.setValue("True or False. @Directive is used for creating custom directives.");
		Question q18 = new Question();
		q18.setLibrary(lib1);
		q18.setDifficulty(1);
		q18.setValue("True or False. @Component is a special form of the @Directive decorator.");
		Question q19 = new Question();
		q19.setLibrary(lib1);
		q19.setDifficulty(1);
		q19.setValue("Which of the following are the three types of directives in Angular 2? (Choose all that apply)");
		Question q20 = new Question();
		q20.setLibrary(lib1);
		q20.setDifficulty(1);
		q20.setValue("True or False. Property-binding and interpolation can be used to set an element's property for string values.");
		Question q21 = new Question();
		q21.setLibrary(lib1);
		q21.setDifficulty(1);
		q21.setValue("Metadata is: (Choose the best option to complete the sentence).");
		Question q22 = new Question();
		q22.setLibrary(lib1);
		q22.setDifficulty(1);
		q22.setValue("Which of the following decorators is the one used to specify metadata for the root module?");
		Question q23 = new Question();
		q23.setLibrary(lib1);
		q23.setDifficulty(1);
		q23.setValue("Which module defines functionality for running your application in a web browser? (Choose the best option)");
		Question q24 = new Question();
		q24.setLibrary(lib1);
		q24.setDifficulty(1);
		q24.setValue("True or False. All applications have at least one module.");
		Question q25 = new Question();
		q25.setLibrary(lib1);
		q25.setDifficulty(1);
		q25.setValue("Which of the following snippets correctly uses event-binding according to Angular 2 syntax:");
		Question q26 = new Question();
		q26.setLibrary(lib1);
		q26.setDifficulty(1);
		q26.setValue("True or False. The following is an example of event-binding syntax:");
		Question q27 = new Question();
		q27.setLibrary(lib1);
		q27.setDifficulty(1);
		q27.setValue("True or False. Event-binding associates DOM events to component functions.");
		Question q28 = new Question();
		q28.setLibrary(lib1);
		q28.setDifficulty(1);
		q28.setValue("Which of the following correctly uses property binding:");
		Question q29 = new Question();
		q29.setLibrary(lib1);
		q29.setDifficulty(1);
		q29.setValue("True or False. Angular 2 supports TypeScript.");
		Question q30 = new Question();
		q30.setLibrary(lib1);
		q30.setDifficulty(1);
		q30.setValue("What type of framework is Angular2?");
		Question q31 = new Question();
		q31.setLibrary(lib1);
		q31.setDifficulty(1);
		q31.setValue("True or False. The AppComponent is typically the name for an Angular 2 application's root component.");
		Question q32 = new Question();
		q32.setLibrary(lib1);
		q32.setDifficulty(1);
		q32.setValue("Which of the following files is typically used to link your application's components?");
		Question q33 = new Question();
		q33.setLibrary(lib1);
		q33.setDifficulty(1);
		q33.setValue("Data-binding is: (Choose the best option to complete this sentence)");
		
		Answer a1 = new Answer();
		a1.setQuestion(q1);
		a1.setCorrect(false);
		a1.setValue("true");
		Answer a2 = new Answer();
		a2.setQuestion(q1);
		a2.setCorrect(true);
		a2.setValue("false");
		Answer a3 = new Answer();
		a3.setQuestion(q2);
		a3.setCorrect(false);
		a3.setValue("true");
		Answer a4 = new Answer();
		a4.setQuestion(q2);
		a4.setCorrect(true);
		a4.setValue("false");
		Answer a5 = new Answer();
		a5.setQuestion(q3);
		a5.setCorrect(true);
		a5.setValue("ngModel");
		Answer a6 = new Answer();
		a6.setQuestion(q3);
		a6.setCorrect(true);
		a6.setValue("ngClass");
		Answer a7 = new Answer();
		a7.setQuestion(q3);
		a7.setCorrect(false);
		a7.setValue("ngFor");
		Answer a8 = new Answer();
		a8.setQuestion(q3);
		a8.setCorrect(false);
		a8.setValue("ngIf");
		Answer a9 = new Answer();
		a9.setQuestion(q4);
		a9.setCorrect(false);
		a9.setValue("true");
		Answer a10 = new Answer();
		a10.setQuestion(q4);
		a10.setCorrect(true);
		a10.setValue("false");
		Answer a11 = new Answer();
		a11.setQuestion(q5);
		a11.setCorrect(false);
		a11.setValue("true");
		Answer a12 = new Answer();
		a12.setQuestion(q5);
		a12.setCorrect(true);
		a12.setValue("false");
		Answer a13 = new Answer();
		a13.setQuestion(q6);
		a13.setCorrect(true);
		a13.setValue("true");
		Answer a14 = new Answer();
		a14.setQuestion(q6);
		a14.setCorrect(false);
		a14.setValue("false");
		Answer a15 = new Answer();
		a15.setQuestion(q7);
		a15.setCorrect(true);
		a15.setValue("@angular/core");
		Answer a16 = new Answer();
		a16.setQuestion(q7);
		a16.setCorrect(false);
		a16.setValue("@angular/http");
		Answer a17 = new Answer();
		a17.setQuestion(q7);
		a17.setCorrect(false);
		a17.setValue("@angular/component");
		Answer a18 = new Answer();
		a18.setQuestion(q7);
		a18.setCorrect(false);
		a18.setValue("@angular/directives");
		Answer a19 = new Answer();
		a19.setQuestion(q8);
		a19.setCorrect(false);
		a19.setValue("animations");
		Answer a20 = new Answer();
		a20.setQuestion(q8);
		a20.setCorrect(false);
		a20.setValue("exportAs");
		Answer a21 = new Answer();
		a21.setQuestion(q8);
		a21.setCorrect(false);
		a21.setValue("providers");
		Answer a22 = new Answer();
		a22.setQuestion(q8);
		a22.setCorrect(false);
		a22.setValue("template");
		Answer a23 = new Answer();
		a23.setQuestion(q8);
		a23.setCorrect(true);
		a23.setValue("templateUrl");
		Answer a24 = new Answer();
		a24.setQuestion(q9);
		a24.setCorrect(true);
		a24.setValue("imports");
		Answer a25 = new Answer();
		a25.setQuestion(q9);
		a25.setCorrect(true);
		a25.setValue("providers");
		Answer a26 = new Answer();
		a26.setQuestion(q9);
		a26.setCorrect(false);
		a26.setValue("pipes");
		Answer a27 = new Answer();
		a27.setQuestion(q9);
		a27.setCorrect(true);
		a27.setValue("bootstrap");
		Answer a28 = new Answer();
		a28.setQuestion(q9);
		a28.setCorrect(false);
		a28.setValue("directives");
		Answer a29 = new Answer();
		a29.setQuestion(q10);
		a29.setCorrect(true);
		a29.setValue("<script> tags");
		Answer a30 = new Answer();
		a30.setQuestion(q10);
		a30.setCorrect(true);
		a30.setValue("<html> tags");
		Answer a31 = new Answer();
		a31.setQuestion(q10);
		a31.setCorrect(false);
		a31.setValue("<p> tags");
		Answer a32 = new Answer();
		a32.setQuestion(q10);
		a32.setCorrect(false);
		a32.setValue("<div> tags");
		Answer a33 = new Answer();
		a33.setQuestion(q11);
		a33.setCorrect(false);
		a33.setValue("imports");
		Answer a34 = new Answer();
		a34.setQuestion(q11);
		a34.setCorrect(true);
		a34.setValue("providers");
		Answer a35 = new Answer();
		a35.setQuestion(q11);
		a35.setCorrect(false);
		a35.setValue("declarations");
		Answer a36 = new Answer();
		a36.setQuestion(q11);
		a36.setCorrect(false);
		a36.setValue("exports");
		Answer a37 = new Answer();
		a37.setQuestion(q11);
		a37.setCorrect(false);
		a37.setValue("bootstrap");
		Answer a38 = new Answer();
		a38.setQuestion(q12);
		a38.setCorrect(false);
		a38.setValue("animations");
		Answer a39 = new Answer();
		a39.setQuestion(q12);
		a39.setCorrect(false);
		a39.setValue("moduleId");
		Answer a40 = new Answer();
		a40.setQuestion(q12);
		a40.setCorrect(false);
		a40.setValue("exportAs");
		Answer a41 = new Answer();
		a41.setQuestion(q12);
		a41.setCorrect(false);
		a41.setValue("providers");
		Answer a42 = new Answer();
		a42.setQuestion(q12);
		a42.setCorrect(true);
		a42.setValue("selector");
		Answer a43 = new Answer();
		a43.setQuestion(q13);
		a43.setCorrect(false);
		a43.setValue("imports");
		Answer a44 = new Answer();
		a44.setQuestion(q13);
		a44.setCorrect(true);
		a44.setValue("providers");
		Answer a45 = new Answer();
		a45.setQuestion(q13);
		a45.setCorrect(false);
		a45.setValue("declarations");
		Answer a46 = new Answer();
		a46.setQuestion(q13);
		a46.setCorrect(false);
		a46.setValue("exports");
		Answer a47 = new Answer();
		a47.setQuestion(q13);
		a47.setCorrect(false);
		a47.setValue("bootstrap");
		Answer a48 = new Answer();
		a48.setQuestion(q14);
		a48.setCorrect(true);
		a48.setValue("@Injectable");
		Answer a49 = new Answer();
		a49.setQuestion(q14);
		a49.setCorrect(false);
		a49.setValue("@Component");
		Answer a50 = new Answer();
		a50.setQuestion(q14);
		a50.setCorrect(false);
		a50.setValue("@NgModule");
		Answer a51 = new Answer();
		a51.setQuestion(q14);
		a51.setCorrect(false);
		a51.setValue("@Directive");
		Answer a52 = new Answer();
		a52.setQuestion(q15);
		a52.setCorrect(false);
		a52.setValue("true");
		Answer a53 = new Answer();
		a53.setQuestion(q15);
		a53.setCorrect(true);
		a53.setValue("false");
		Answer a54 = new Answer();
		a54.setQuestion(q16);
		a54.setCorrect(false);
		a54.setValue("true");
		Answer a55 = new Answer();
		a55.setQuestion(q16);
		a55.setCorrect(true);
		a55.setValue("false");
		Answer a56 = new Answer();
		a56.setQuestion(q17);
		a56.setCorrect(true);
		a56.setValue("true");
		Answer a57 = new Answer();
		a57.setQuestion(q17);
		a57.setCorrect(false);
		a57.setValue("false");
		Answer a58 = new Answer();
		a58.setQuestion(q18);
		a58.setCorrect(true);
		a58.setValue("true");
		Answer a59 = new Answer();
		a59.setQuestion(q18);
		a59.setCorrect(false);
		a59.setValue("false");
		Answer a60 = new Answer();
		a60.setQuestion(q19);
		a60.setCorrect(true);
		a60.setValue("@Directive (custom)");
		Answer a61 = new Answer();
		a61.setQuestion(q19);
		a61.setCorrect(true);
		a61.setValue("structural");
		Answer a62 = new Answer();
		a62.setQuestion(q19);
		a62.setCorrect(true);
		a62.setValue("attribute");
		Answer a63 = new Answer();
		a63.setQuestion(q19);
		a63.setCorrect(false);
		a63.setValue("behavioral");
		Answer a64 = new Answer();
		a64.setQuestion(q19);
		a64.setCorrect(false);
		a64.setValue("elemental");
		Answer a65 = new Answer();
		a65.setQuestion(q20);
		a65.setCorrect(true);
		a65.setValue("true");
		Answer a66 = new Answer();
		a66.setQuestion(q20);
		a66.setCorrect(false);
		a66.setValue("false");
		Answer a67 = new Answer();
		a67.setQuestion(q21);
		a67.setCorrect(false);
		a67.setValue("the association of data/events with elements and user interactions");
		Answer a68 = new Answer();
		a68.setQuestion(q21);
		a68.setCorrect(false);
		a68.setValue("elements, attributes and CSS style classes that you bind on your HTML templates");
		Answer a69 = new Answer();
		a69.setQuestion(q21);
		a69.setCorrect(false);
		a69.setValue("a set of instructions solely dedicated towards presentation logic");
		Answer a70 = new Answer();
		a70.setQuestion(q21);
		a70.setCorrect(true);
		a70.setValue("a collection of data values that you pass to a component");
		Answer a71 = new Answer();
		a71.setQuestion(q22);
		a71.setCorrect(true);
		a71.setValue("@NgModule");
		Answer a72 = new Answer();
		a72.setQuestion(q22);
		a72.setCorrect(false);
		a72.setValue("@Module");
		Answer a73 = new Answer();
		a73.setQuestion(q22);
		a73.setCorrect(false);
		a73.setValue("@Component");
		Answer a74 = new Answer();
		a74.setQuestion(q22);
		a74.setCorrect(false);
		a74.setValue("@Injectable");
		Answer a75 = new Answer();
		a75.setQuestion(q23);
		a75.setCorrect(false);
		a75.setValue("HTTPModule");
		Answer a76 = new Answer();
		a76.setQuestion(q23);
		a76.setCorrect(true);
		a76.setValue("BrowserModule");
		Answer a77 = new Answer();
		a77.setQuestion(q23);
		a77.setCorrect(false);
		a77.setValue("AJAXModule");
		Answer a78 = new Answer();
		a78.setQuestion(q23);
		a78.setCorrect(false);
		a78.setValue("HTMLModule");
		Answer a79 = new Answer();
		a79.setQuestion(q24);
		a79.setCorrect(true);
		a79.setValue("true");
		Answer a80 = new Answer();
		a80.setQuestion(q24);
		a80.setCorrect(false);
		a80.setValue("false");
		Answer a81 = new Answer();
		a81.setQuestion(q25);
		a81.setCorrect(true);
		a81.setValue("<button (click)=\"func\">…");
		Answer a82 = new Answer();
		a82.setQuestion(q25);
		a82.setCorrect(false);
		a82.setValue("<button click=\"func\"> …");
		Answer a83 = new Answer();
		a83.setQuestion(q25);
		a83.setCorrect(false);
		a83.setValue("<button [click]=\"func\">");
		Answer a84 = new Answer();
		a84.setQuestion(q25);
		a84.setCorrect(false);
		a84.setValue("<button onclick=\"func\">");
		Answer a85 = new Answer();
		a85.setQuestion(q26);
		a85.setCorrect(false);
		a85.setValue("true");
		Answer a86 = new Answer();
		a86.setQuestion(q26);
		a86.setCorrect(true);
		a86.setValue("false");
		Answer a87 = new Answer();
		a87.setQuestion(q27);
		a87.setCorrect(true);
		a87.setValue("true");
		Answer a88 = new Answer();
		a88.setQuestion(q27);
		a88.setCorrect(false);
		a88.setValue("false");
		Answer a89 = new Answer();
		a89.setQuestion(q28);
		a89.setCorrect(false);
		a89.setValue("<img src=\"{{ value }}\" />");
		Answer a90 = new Answer();
		a90.setQuestion(q28);
		a90.setCorrect(false);
		a90.setValue("<img src=\"value\" />");
		Answer a91 = new Answer();
		a91.setQuestion(q28);
		a91.setCorrect(false);
		a91.setValue("<img src=value />");
		Answer a92 = new Answer();
		a92.setQuestion(q28);
		a92.setCorrect(true);
		a92.setValue("<img [src]=\"value\" />");
		Answer a93 = new Answer();
		a93.setQuestion(q28);
		a93.setCorrect(false);
		a93.setValue("<img (src)=\"value\" />");
		Answer a94 = new Answer();
		a94.setQuestion(q29);
		a94.setCorrect(true);
		a94.setValue("true");
		Answer a95 = new Answer();
		a95.setQuestion(q29);
		a95.setCorrect(false);
		a95.setValue("false");
		Answer a96 = new Answer();
		a96.setQuestion(q30);
		a96.setCorrect(false);
		a96.setValue("MVVM (Model-View-View-Model)");
		Answer a97 = new Answer();
		a97.setQuestion(q30);
		a97.setCorrect(false);
		a97.setValue("MVC (Model-View-Controller)");
		Answer a98 = new Answer();
		a98.setQuestion(q30);
		a98.setCorrect(true);
		a98.setValue("MVW (Model-View-Whatever)");
		Answer a99 = new Answer();
		a99.setQuestion(q30);
		a99.setCorrect(false);
		a99.setValue("MVM (Model-View-Model)");
		Answer a100 = new Answer();
		a100.setQuestion(q31);
		a100.setCorrect(true);
		a100.setValue("true");
		Answer a101 = new Answer();
		a101.setQuestion(q31);
		a101.setCorrect(false);
		a101.setValue("false");
		Answer a102 = new Answer();
		a102.setQuestion(q32);
		a102.setCorrect(false);
		a102.setValue("app.component.ts");
		Answer a103 = new Answer();
		a103.setQuestion(q32);
		a103.setCorrect(true);
		a103.setValue("app.module.ts");
		Answer a104 = new Answer();
		a104.setQuestion(q32);
		a104.setCorrect(false);
		a104.setValue("main.ts");
		Answer a105 = new Answer();
		a105.setQuestion(q32);
		a105.setCorrect(false);
		a105.setValue("main.js");
		Answer a106 = new Answer();
		a106.setQuestion(q33);
		a106.setCorrect(true);
		a106.setValue("the association of data/events with elements and user interactions");
		Answer a107 = new Answer();
		a107.setQuestion(q33);
		a107.setCorrect(false);
		a107.setValue("elements, attributes and CSS style classes that you bind on your HTML templates");
		Answer a108 = new Answer();
		a108.setQuestion(q33);
		a108.setCorrect(false);
		a108.setValue("a set of instructions solely dedicated towards presentation logic");
		Answer a109 = new Answer();
		a109.setQuestion(q33);
		a109.setCorrect(false);
		a109.setValue("a collection of data values that you pass to a component");
		
		s.save(q1);
		s.save(q2);
		s.save(q3);
		s.save(q4);
		s.save(q5);
		s.save(q6);
		s.save(q7);
		s.save(q8);
		s.save(q9);
		s.save(q10);
		s.save(q11);
		s.save(q12);
		s.save(q13);
		s.save(q14);
		s.save(q15);
		s.save(q16);
		s.save(q17);
		s.save(q18);
		s.save(q19);
		s.save(q20);
		s.save(q21);
		s.save(q22);
		s.save(q23);
		s.save(q24);
		s.save(q25);
		s.save(q26);
		s.save(q27);
		s.save(q28);
		s.save(q29);
		s.save(q30);
		s.save(q31);
		s.save(q32);
		s.save(q33);
		
		s.save(a1);
		s.save(a2);
		s.save(a3);
		s.save(a4);
		s.save(a5);
		s.save(a6);
		s.save(a7);
		s.save(a8);
		s.save(a9);
		s.save(a10);
		s.save(a11);
		s.save(a12);
		s.save(a13);
		s.save(a14);
		s.save(a15);
		s.save(a16);
		s.save(a17);
		s.save(a18);
		s.save(a19);
		s.save(a20);
		s.save(a21);
		s.save(a22);
		s.save(a23);
		s.save(a24);
		s.save(a25);
		s.save(a26);
		s.save(a27);
		s.save(a28);
		s.save(a29);
		s.save(a30);
		s.save(a31);
		s.save(a32);
		s.save(a33);
		s.save(a34);
		s.save(a35);
		s.save(a36);
		s.save(a37);
		s.save(a38);
		s.save(a39);
		s.save(a40);
		s.save(a41);
		s.save(a42);
		s.save(a43);
		s.save(a44);
		s.save(a45);
		s.save(a46);
		s.save(a47);
		s.save(a48);
		s.save(a49);
		s.save(a50);
		s.save(a51);
		s.save(a52);
		s.save(a53);
		s.save(a54);
		s.save(a55);
		s.save(a56);
		s.save(a57);
		s.save(a58);
		s.save(a59);
		s.save(a60);
		s.save(a61);
		s.save(a62);
		s.save(a63);
		s.save(a64);
		s.save(a65);
		s.save(a66);
		s.save(a67);
		s.save(a68);
		s.save(a69);
		s.save(a70);
		s.save(a71);
		s.save(a72);
		s.save(a73);
		s.save(a74);
		s.save(a75);
		s.save(a76);
		s.save(a77);
		s.save(a78);
		s.save(a79);
		s.save(a80);
		s.save(a81);
		s.save(a82);
		s.save(a83);
		s.save(a84);
		s.save(a85);
		s.save(a86);
		s.save(a87);
		s.save(a88);
		s.save(a89);
		s.save(a90);
		s.save(a91);
		s.save(a92);
		s.save(a93);
		s.save(a94);
		s.save(a95);
		s.save(a96);
		s.save(a97);
		s.save(a98);
		s.save(a99);
		s.save(a100);
		s.save(a101);
		s.save(a102);
		s.save(a103);
		s.save(a104);
		s.save(a105);
		s.save(a106);
		s.save(a107);
		s.save(a108);
		s.save(a109);
		
		Account acc2 = new Account();
		acc2.setAdmin(false);
		acc2.setEmail("dave.guido.brewer@gmail.com");
		acc2.setUsername("dbrewer");
		acc2.setPassword("password2");
		s.save(acc2);
		
		Library lib2 = new Library();
		lib2.setName("Servlets");
		lib2.setStatus(Status.PRIVATE);
		lib2.setAccount(acc2);
		s.save(lib2);
		
		Question qq1 = new Question();
		qq1.setLibrary(lib2);
		qq1.setDifficulty(1);
		qq1.setValue("How would you pre-initialize a servlet?");
		Question qq2 = new Question();
		qq2.setLibrary(lib2);
		qq2.setDifficulty(1);
		qq2.setValue("To handle exceptions in servlets and JSPs, you would have to use the ____ element in web.xml to specify the invocation of servlets in response to certain exception class types or HTTP status codes.");
		Question qq3 = new Question();
		qq3.setLibrary(lib2);
		qq3.setDifficulty(1);
		qq3.setValue("What is the method signature of the doPost method?");
		Question qq4 = new Question();
		qq4.setLibrary(lib2);
		qq4.setDifficulty(1);
		qq4.setValue("What is the difference between ServletConfig and ServletContext?");
		Question qq5 = new Question();
		qq5.setLibrary(lib2);
		qq5.setDifficulty(1);
		qq5.setValue("What is the difference between HTTP GET and POST methods?");
		Question qq6 = new Question();
		qq6.setLibrary(lib2);
		qq6.setDifficulty(1);
		qq6.setValue("What is the difference between request.getRequestDispatcher forward and response sendRedirect?");
		Question qq7 = new Question();
		qq7.setLibrary(lib2);
		qq7.setDifficulty(1);
		qq7.setValue("Which is NOT a way of persisting state in a JEE application?");
		Question qq8 = new Question();
		qq8.setLibrary(lib2);
		qq8.setDifficulty(1);
		qq8.setValue("Which of the following is not a valid tag in the web.xml for handling errors?");
		Question qq9 = new Question();
		qq9.setLibrary(lib2);
		qq9.setDifficulty(1);
		qq9.setValue("Using the post http method we can send data in the URL and in the request body");
		Question qq10 = new Question();
		qq10.setLibrary(lib2);
		qq10.setDifficulty(1);
		qq10.setValue("True or False. When a servlet throws an exception, the web container searches the configurations in web.xml that use the exception-type element for a match with the thrown exception type.");
		Question qq11 = new Question();
		qq11.setLibrary(lib2);
		qq11.setDifficulty(1);
		qq11.setValue("Which tag in web.xml is used to add values to the ServletContext object?");
		Question qq12 = new Question();
		qq12.setLibrary(lib2);
		qq12.setDifficulty(1);
		qq12.setValue("Which tag in web.xml is used to add values to the ServletConfig object?");
		Question qq13 = new Question();
		qq13.setLibrary(lib2);
		qq13.setDifficulty(1);
		qq13.setValue("Which tags are used to register a servlet in web.xml?");
		Question qq14 = new Question();
		qq14.setLibrary(lib2);
		qq14.setDifficulty(1);
		qq14.setValue("Which tags are used to map HTTP traffic a servlet in web.xml?");
		Question qq15 = new Question();
		qq15.setLibrary(lib2);
		qq15.setDifficulty(1);
		qq15.setValue("The service method delegates to either doGet or doPost (or one of the other do methods) for each request.");
		Question qq16 = new Question();
		qq16.setLibrary(lib2);
		qq16.setDifficulty(1);
		qq16.setValue("The init method is called once during the lifecycle of a servlet.");
		Question qq17 = new Question();
		qq17.setLibrary(lib2);
		qq17.setDifficulty(1);
		qq17.setValue("The destroy method in the lifecycle of a servlet destroys the current thread for the servlet but not the servlet object.");
		Question qq18 = new Question();
		qq18.setLibrary(lib2);
		qq18.setDifficulty(1);
		qq18.setValue("How do you write a message back to the browser from inside a Servlet?");
		Question qq19 = new Question();
		qq19.setLibrary(lib2);
		qq19.setDifficulty(1);
		qq19.setValue("XML is case sensitive and is used to store metadata.");
		Question qq20 = new Question();
		qq20.setLibrary(lib2);
		qq20.setDifficulty(1);
		qq20.setValue("GenericServlet implements Servlet interface.");
		Question qq21 = new Question();
		qq21.setLibrary(lib2);
		qq21.setDifficulty(1);
		qq21.setValue("Session.getParameter is used to gather user input.");
		Question qq22 = new Question();
		qq22.setLibrary(lib2);
		qq22.setDifficulty(1);
		qq22.setValue("Response.sendRedirect returns a status code in the 300s.");
		Question qq23 = new Question();
		qq23.setLibrary(lib2);
		qq23.setDifficulty(1);
		qq23.setValue("By default, instance variables are thread-safe in a servlet.");
		Question qq24 = new Question();
		qq24.setLibrary(lib2);
		qq24.setDifficulty(1);
		qq24.setValue("By default, when is a servlet first instantiated and loaded onto the Servlet Container?");
		Question qq25 = new Question();
		qq25.setLibrary(lib2);
		qq25.setDifficulty(1);
		qq25.setValue("What is the filename of the deployment descriptor?");
		Question qq26 = new Question();
		qq26.setLibrary(lib2);
		qq26.setDifficulty(1);
		qq26.setValue("True or False. The Front Controller design pattern is primarily used in web-applications.");
		Question qq27 = new Question();
		qq27.setLibrary(lib2);
		qq27.setDifficulty(1);
		qq27.setValue("What does a Front Controller do?");
		Question qq28 = new Question();
		qq28.setLibrary(lib2);
		qq28.setDifficulty(1);
		qq28.setValue("What is NOT true about the JSessionID?");
		Question qq29 = new Question();
		qq29.setLibrary(lib2);
		qq29.setDifficulty(1);
		qq29.setValue("The method used to retrieve HTML form data from a HttpServletRequest is?");
		Question qq30 = new Question();
		qq30.setLibrary(lib2);
		qq30.setDifficulty(1);
		qq30.setValue("Which of these is a benefit to using sendRedirect()?");
		
		Answer aa1 = new Answer();
		aa1.setQuestion(qq1);
		aa1.setCorrect(true);
		aa1.setValue("Override the init( ) method");
		Answer aa2 = new Answer();
		aa2.setQuestion(qq1);
		aa2.setCorrect(false);
		aa2.setValue("Override the init(ServletConfig config) method");
		Answer aa3 = new Answer();
		aa3.setQuestion(qq1);
		aa3.setCorrect(false);
		aa3.setValue("Use the load-on-startup tag");
		Answer aa4 = new Answer();
		aa4.setQuestion(qq1);
		aa4.setCorrect(false);
		aa4.setValue("You cannot pre-initialize a servlet");
		Answer aa5 = new Answer();
		aa5.setQuestion(qq2);
		aa5.setCorrect(true);
		aa5.setValue("error-page");
		Answer aa6 = new Answer();
		aa6.setQuestion(qq2);
		aa6.setCorrect(false);
		aa6.setValue("error");
		Answer aa7 = new Answer();
		aa7.setQuestion(qq2);
		aa7.setCorrect(false);
		aa7.setValue("error-handler");
		Answer aa8 = new Answer();
		aa8.setQuestion(qq2);
		aa8.setCorrect(false);
		aa8.setValue("None of the above");
		Answer aa9 = new Answer();
		aa9.setQuestion(qq3);
		aa9.setCorrect(false);
		aa9.setValue("public void doPost(HttpServletRequest request, HttpServletResponse response)");
		Answer aa10 = new Answer();
		aa10.setQuestion(qq3);
		aa10.setCorrect(true);
		aa10.setValue("protected void doPost(HttpServletRequest request, HttpServletResponse response)");
		Answer aa11 = new Answer();
		aa11.setQuestion(qq3);
		aa11.setCorrect(false);
		aa11.setValue("public PrintWriter doPost(HttpServletRequest request)");
		Answer aa12 = new Answer();
		aa12.setQuestion(qq3);
		aa12.setCorrect(false);
		aa12.setValue("protected HttpServletResponse doPost(HttpServletRequest request)");
		Answer aa13 = new Answer();
		aa13.setQuestion(qq4);
		aa13.setCorrect(false);
		aa13.setValue("ServletConfig is available to all servlets. ServletContext is available to only one servlet.");
		Answer aa14 = new Answer();
		aa14.setQuestion(qq4);
		aa14.setCorrect(true);
		aa14.setValue("ServletContext is available to all servlets. ServletConfig is available to only one servlet.");
		Answer aa15 = new Answer();
		aa15.setQuestion(qq4);
		aa15.setCorrect(false);
		aa15.setValue("ServletConfig object is only available in a JSP.");
		Answer aa16 = new Answer();
		aa16.setQuestion(qq4);
		aa16.setCorrect(false);
		aa16.setValue("ServletContext object is only available in a Servlet and not a JSP.");
		Answer aa17 = new Answer();
		aa17.setQuestion(qq5);
		aa17.setCorrect(false);
		aa17.setValue("GET requests are never cached");
		Answer aa18 = new Answer();
		aa18.setQuestion(qq5);
		aa18.setCorrect(false);
		aa18.setValue("GET requests do not remain in the browser history");
		Answer aa19 = new Answer();
		aa19.setQuestion(qq5);
		aa19.setCorrect(true);
		aa19.setValue("POST requests cannot be bookmarked");
		Answer aa20 = new Answer();
		aa20.setQuestion(qq5);
		aa20.setCorrect(false);
		aa20.setValue("GET requests have no restrictions on data length");
		Answer aa21 = new Answer();
		aa21.setQuestion(qq6);
		aa21.setCorrect(false);
		aa21.setValue("Forward is performed internally by the client");
		Answer aa22 = new Answer();
		aa22.setQuestion(qq6);
		aa22.setCorrect(true);
		aa22.setValue("Browser is completely unaware that a forward has taken place, so its original URL remains intact");
		Answer aa23 = new Answer();
		aa23.setQuestion(qq6);
		aa23.setCorrect(false);
		aa23.setValue("Forward is marginally slower than a redirect, since it requires two browser requests, not one");
		Answer aa24 = new Answer();
		aa24.setQuestion(qq6);
		aa24.setCorrect(false);
		aa24.setValue("With forward, objects placed in the original request scope are not available to the second request");
		Answer aa25 = new Answer();
		aa25.setQuestion(qq7);
		aa25.setCorrect(false);
		aa25.setValue("Cookies");
		Answer aa26 = new Answer();
		aa26.setQuestion(qq7);
		aa26.setCorrect(false);
		aa26.setValue("Session object");
		Answer aa27 = new Answer();
		aa27.setQuestion(qq7);
		aa27.setCorrect(true);
		aa27.setValue("WAR file");
		Answer aa28 = new Answer();
		aa28.setQuestion(qq7);
		aa28.setCorrect(false);
		aa28.setValue("URL rewriting");
		Answer aa29 = new Answer();
		aa29.setQuestion(qq8);
		aa29.setCorrect(false);
		aa29.setValue("error-code");
		Answer aa30 = new Answer();
		aa30.setQuestion(qq8);
		aa30.setCorrect(false);
		aa30.setValue("exception-type");
		Answer aa31 = new Answer();
		aa31.setQuestion(qq8);
		aa31.setCorrect(false);
		aa31.setValue("location");
		Answer aa32 = new Answer();
		aa32.setQuestion(qq8);
		aa32.setCorrect(true);
		aa32.setValue("url-pattern");
		Answer aa33 = new Answer();
		aa33.setQuestion(qq9);
		aa33.setCorrect(true);
		aa33.setValue("false");
		Answer aa34 = new Answer();
		aa34.setQuestion(qq9);
		aa34.setCorrect(false);
		aa34.setValue("false");
		Answer aa35 = new Answer();
		aa35.setQuestion(qq10);
		aa35.setCorrect(true);
		aa35.setValue("false");
		Answer aa36 = new Answer();
		aa36.setQuestion(qq10);
		aa36.setCorrect(false);
		aa36.setValue("false");
		Answer aa37 = new Answer();
		aa37.setQuestion(qq11);
		aa37.setCorrect(true);
		aa37.setValue("context-param");
		Answer aa38 = new Answer();
		aa38.setQuestion(qq11);
		aa38.setCorrect(false);
		aa38.setValue("init-param");
		Answer aa39 = new Answer();
		aa39.setQuestion(qq11);
		aa39.setCorrect(false);
		aa39.setValue("servlet-param");
		Answer aa40 = new Answer();
		aa40.setQuestion(qq11);
		aa40.setCorrect(false);
		aa40.setValue("config-param");
		Answer aa41 = new Answer();
		aa41.setQuestion(qq12);
		aa41.setCorrect(false);
		aa41.setValue("context-param");
		Answer aa42 = new Answer();
		aa42.setQuestion(qq12);
		aa42.setCorrect(true);
		aa42.setValue("init-param");
		Answer aa43 = new Answer();
		aa43.setQuestion(qq12);
		aa43.setCorrect(false);
		aa43.setValue("servlet-param");
		Answer aa44 = new Answer();
		aa44.setQuestion(qq12);
		aa44.setCorrect(false);
		aa44.setValue("config-param");
		Answer aa45 = new Answer();
		aa45.setQuestion(qq13);
		aa45.setCorrect(true);
		aa45.setValue("servlet, servlet-name, servlet-class");
		Answer aa46 = new Answer();
		aa46.setQuestion(qq13);
		aa46.setCorrect(false);
		aa46.setValue("servlet, servlet-class");
		Answer aa47 = new Answer();
		aa47.setQuestion(qq13);
		aa47.setCorrect(false);
		aa47.setValue("servlet, servlet-name");
		Answer aa48 = new Answer();
		aa48.setQuestion(qq13);
		aa48.setCorrect(false);
		aa48.setValue("servlet");
		Answer aa49 = new Answer();
		aa49.setQuestion(qq14);
		aa49.setCorrect(true);
		aa49.setValue("servlet-mapping, servlet-name, url-pattern");
		Answer aa50 = new Answer();
		aa50.setQuestion(qq14);
		aa50.setCorrect(false);
		aa50.setValue("servlet-mapper, servlet-name, url");
		Answer aa51 = new Answer();
		aa51.setQuestion(qq14);
		aa51.setCorrect(false);
		aa51.setValue("servlet-map, url-pattern");
		Answer aa52 = new Answer();
		aa52.setQuestion(qq14);
		aa52.setCorrect(false);
		aa52.setValue("servlet-mapping, servlet-name, servlet-class");
		Answer aa53 = new Answer();
		aa53.setQuestion(qq15);
		aa53.setCorrect(true);
		aa53.setValue("false");
		Answer aa54 = new Answer();
		aa54.setQuestion(qq15);
		aa54.setCorrect(false);
		aa54.setValue("false");
		Answer aa55 = new Answer();
		aa55.setQuestion(qq16);
		aa55.setCorrect(true);
		aa55.setValue("false");
		Answer aa56 = new Answer();
		aa56.setQuestion(qq16);
		aa56.setCorrect(false);
		aa56.setValue("false");
		Answer aa57 = new Answer();
		aa57.setQuestion(qq17);
		aa57.setCorrect(false);
		aa57.setValue("false");
		Answer aa58 = new Answer();
		aa58.setQuestion(qq17);
		aa58.setCorrect(true);
		aa58.setValue("false");
		Answer aa59 = new Answer();
		aa59.setQuestion(qq18);
		aa59.setCorrect(true);
		aa59.setValue("PrintWriter out = response.getWriter( ) out.println(HTML code)");
		Answer aa60 = new Answer();
		aa60.setQuestion(qq18);
		aa60.setCorrect(false);
		aa60.setValue("HttpWriter out = response.getHttpWriter( ) out.println(HTML code)");
		Answer aa61 = new Answer();
		aa61.setQuestion(qq18);
		aa61.setCorrect(false);
		aa61.setValue("HtmlWriter out = response.get HtmlWriter ( ) out.println(HTML code)");
		Answer aa62 = new Answer();
		aa62.setQuestion(qq18);
		aa62.setCorrect(false);
		aa62.setValue("BufferedWriter writer = new BufferedWriter(new FileWriter()) writer.write(HTML code)");
		Answer aa63 = new Answer();
		aa63.setQuestion(qq19);
		aa63.setCorrect(true);
		aa63.setValue("false");
		Answer aa64 = new Answer();
		aa64.setQuestion(qq19);
		aa64.setCorrect(false);
		aa64.setValue("false");
		Answer aa65 = new Answer();
		aa65.setQuestion(qq20);
		aa65.setCorrect(true);
		aa65.setValue("false");
		Answer aa66 = new Answer();
		aa66.setQuestion(qq20);
		aa66.setCorrect(false);
		aa66.setValue("false");
		Answer aa67 = new Answer();
		aa67.setQuestion(qq21);
		aa67.setCorrect(false);
		aa67.setValue("false");
		Answer aa68 = new Answer();
		aa68.setQuestion(qq21);
		aa68.setCorrect(true);
		aa68.setValue("false");
		Answer aa69 = new Answer();
		aa69.setQuestion(qq22);
		aa69.setCorrect(true);
		aa69.setValue("false");
		Answer aa70 = new Answer();
		aa70.setQuestion(qq22);
		aa70.setCorrect(false);
		aa70.setValue("false");
		Answer aa71 = new Answer();
		aa71.setQuestion(qq23);
		aa71.setCorrect(false);
		aa71.setValue("false");
		Answer aa72 = new Answer();
		aa72.setQuestion(qq23);
		aa72.setCorrect(true);
		aa72.setValue("false");
		Answer aa73 = new Answer();
		aa73.setQuestion(qq24);
		aa73.setCorrect(false);
		aa73.setValue("When the web app starts up");
		Answer aa74 = new Answer();
		aa74.setQuestion(qq24);
		aa74.setCorrect(false);
		aa74.setValue("When the main method is called");
		Answer aa75 = new Answer();
		aa75.setQuestion(qq24);
		aa75.setCorrect(false);
		aa75.setValue("When the servlet container calls the init( ) method");
		Answer aa76 = new Answer();
		aa76.setQuestion(qq24);
		aa76.setCorrect(true);
		aa76.setValue("When it is first requested by a user.");
		Answer aa77 = new Answer();
		aa77.setQuestion(qq25);
		aa77.setCorrect(false);
		aa77.setValue("web.properties");
		Answer aa78 = new Answer();
		aa78.setQuestion(qq25);
		aa78.setCorrect(false);
		aa78.setValue("web.html");
		Answer aa79 = new Answer();
		aa79.setQuestion(qq25);
		aa79.setCorrect(true);
		aa79.setValue("web.xml");
		Answer aa80 = new Answer();
		aa80.setQuestion(qq25);
		aa80.setCorrect(false);
		aa80.setValue("web.xhtml");
		Answer aa81 = new Answer();
		aa81.setQuestion(qq26);
		aa81.setCorrect(true);
		aa81.setValue("false");
		Answer aa82 = new Answer();
		aa82.setQuestion(qq26);
		aa82.setCorrect(false);
		aa82.setValue("false");
		Answer aa83 = new Answer();
		aa83.setQuestion(qq27);
		aa83.setCorrect(true);
		aa83.setValue("intercept all requests and determine whether to forward to a Dispatcher or not");
		Answer aa84 = new Answer();
		aa84.setQuestion(qq27);
		aa84.setCorrect(false);
		aa84.setValue("intercept all responses and customizes the data format for clients");
		Answer aa85 = new Answer();
		aa85.setQuestion(qq27);
		aa85.setCorrect(false);
		aa85.setValue("perform data access for particular views and performs authentication to the database");
		Answer aa86 = new Answer();
		aa86.setQuestion(qq27);
		aa86.setCorrect(false);
		aa86.setValue("manages the Views in the program");
		Answer aa87 = new Answer();
		aa87.setQuestion(qq28);
		aa87.setCorrect(false);
		aa87.setValue("JSessionID is a cookie in J2EE web application which is used in session tracking.");
		Answer aa88 = new Answer();
		aa88.setQuestion(qq28);
		aa88.setCorrect(false);
		aa88.setValue("JSessionID is created by web container upon the first request and is sent along with first response to client.");
		Answer aa89 = new Answer();
		aa89.setQuestion(qq28);
		aa89.setCorrect(false);
		aa89.setValue("Clients forward JSessionID with requests to identify their Session object.");
		Answer aa90 = new Answer();
		aa90.setQuestion(qq28);
		aa90.setCorrect(true);
		aa90.setValue("None of the above.");
		Answer aa91 = new Answer();
		aa91.setQuestion(qq29);
		aa91.setCorrect(false);
		aa91.setValue(".getAttribute()");
		Answer aa92 = new Answer();
		aa92.setQuestion(qq29);
		aa92.setCorrect(true);
		aa92.setValue(".getParameter()");
		Answer aa93 = new Answer();
		aa93.setQuestion(qq29);
		aa93.setCorrect(false);
		aa93.setValue(".getFormField()");
		Answer aa94 = new Answer();
		aa94.setQuestion(qq29);
		aa94.setCorrect(false);
		aa94.setValue(".getField()");
		Answer aa95 = new Answer();
		aa95.setQuestion(qq30);
		aa95.setCorrect(true);
		aa95.setValue("As a clientside operation, the request scope is discarded. Thus, if a user clicks their browser's ?Back? button, any form data stored in the request is lost, which prevents accidental resubmission.");
		Answer aa96 = new Answer();
		aa96.setQuestion(qq30);
		aa96.setCorrect(false);
		aa96.setValue("As a serverside operation, the request scope is preserved. This means that if the user hits their browser's ?Back? button, form data is preserved and a user can view the exact same page they were just looking at.");
		
		s.save(qq1);
		s.save(qq2);
		s.save(qq3);
		s.save(qq4);
		s.save(qq5);
		s.save(qq6);
		s.save(qq7);
		s.save(qq8);
		s.save(qq9);
		s.save(qq10);
		s.save(qq11);
		s.save(qq12);
		s.save(qq13);
		s.save(qq14);
		s.save(qq15);
		s.save(qq16);
		s.save(qq17);
		s.save(qq18);
		s.save(qq19);
		s.save(qq20);
		s.save(qq21);
		s.save(qq22);
		s.save(qq23);
		s.save(qq24);
		s.save(qq25);
		s.save(qq26);
		s.save(qq27);
		s.save(qq28);
		s.save(qq29);
		s.save(qq30);
		
		s.save(aa1);
		s.save(aa2);
		s.save(aa3);
		s.save(aa4);
		s.save(aa5);
		s.save(aa6);
		s.save(aa7);
		s.save(aa8);
		s.save(aa9);
		s.save(aa10);
		s.save(aa11);
		s.save(aa12);
		s.save(aa13);
		s.save(aa14);
		s.save(aa15);
		s.save(aa16);
		s.save(aa17);
		s.save(aa18);
		s.save(aa19);
		s.save(aa20);
		s.save(aa21);
		s.save(aa22);
		s.save(aa23);
		s.save(aa24);
		s.save(aa25);
		s.save(aa26);
		s.save(aa27);
		s.save(aa28);
		s.save(aa29);
		s.save(aa30);
		s.save(aa31);
		s.save(aa32);
		s.save(aa33);
		s.save(aa34);
		s.save(aa35);
		s.save(aa36);
		s.save(aa37);
		s.save(aa38);
		s.save(aa39);
		s.save(aa40);
		s.save(aa41);
		s.save(aa42);
		s.save(aa43);
		s.save(aa44);
		s.save(aa45);
		s.save(aa46);
		s.save(aa47);
		s.save(aa48);
		s.save(aa49);
		s.save(aa50);
		s.save(aa51);
		s.save(aa52);
		s.save(aa53);
		s.save(aa54);
		s.save(aa55);
		s.save(aa56);
		s.save(aa57);
		s.save(aa58);
		s.save(aa59);
		s.save(aa60);
		s.save(aa61);
		s.save(aa62);
		s.save(aa63);
		s.save(aa64);
		s.save(aa65);
		s.save(aa66);
		s.save(aa67);
		s.save(aa68);
		s.save(aa69);
		s.save(aa70);
		s.save(aa71);
		s.save(aa72);
		s.save(aa73);
		s.save(aa74);
		s.save(aa75);
		s.save(aa76);
		s.save(aa77);
		s.save(aa78);
		s.save(aa79);
		s.save(aa80);
		s.save(aa81);
		s.save(aa82);
		s.save(aa83);
		s.save(aa84);
		s.save(aa85);
		s.save(aa86);
		s.save(aa87);
		s.save(aa88);
		s.save(aa89);
		s.save(aa90);
		s.save(aa91);
		s.save(aa92);
		s.save(aa93);
		s.save(aa94);
		s.save(aa95);
		s.save(aa96);
		
		tx.commit();
		
		s.close();
		System.out.println(s.isOpen());
		HibernateUtil.closeSessionFactory();

	}

}
