package com.revature.main;

import org.hibernate.Session;
import org.hibernate.Transaction;

import com.revature.beans.Account;
import com.revature.beans.Answer;
import com.revature.beans.Library;
import com.revature.beans.Question;
import com.revature.beans.Status;
import com.revature.util.HibernateUtil;

public class Driver {

	public static void main(String[] args) {
		init();
	}

	public static void init() {

		Session s = HibernateUtil.getSession();
		System.out.println(s.isOpen());
		Transaction tx = s.getTransaction();
		tx.begin();
		Account acc = new Account();
		acc.setAdmin(true);
		acc.setEmail("collinmeaney375@gmail.com");
		acc.setUsername("cmeaney");
		acc.setPassword("password4");
		s.save(acc);
		Library lib = new Library();
		lib.setName("Angular");
		lib.setStatus(Status.PUBLIC);
		lib.setAccount(acc);
		s.save(lib);
		Question q1 = new Question();
		q1.setLibrary(lib);
		q1.setDifficulty(1);
		q1.setValue("ngFor is used to toggle display of an element.");
		Question q2 = new Question();
		q2.setLibrary(lib);
		q2.setDifficulty(1);
		q2.setValue("True or False. ngIf does NOT remove the element from the DOM if the expression evaluates to false.");
		Question q3 = new Question();
		q3.setLibrary(lib);
		q3.setDifficulty(1);
		q3.setValue("Which of the following are attribute directives? (Choose all that apply)");
		Question q4 = new Question();
		q4.setLibrary(lib);
		q4.setDifficulty(1);
		q4.setValue("True or False. ngClass is used to add/remove multiple styles using key/value pairs of CSS");
		Question q5 = new Question();
		q5.setLibrary(lib);
		q5.setDifficulty(1);
		q5.setValue("True or False. ngStyle is used to manipulate multiple CSS classes.");
		Question q6 = new Question();
		q6.setLibrary(lib);
		q6.setDifficulty(1);
		q6.setValue("True or False. All applications have at least one component, the root component.");
		Question q7 = new Question();
		q7.setLibrary(lib);
		q7.setDifficulty(1);
		q7.setValue("Which of the following libraries defines the @Component decorator? (Choose the best option)");
		Question q8 = new Question();
		q8.setLibrary(lib);
		q8.setDifficulty(1);
		q8.setValue("Which of the following metadata specifies the path to the file that defines the HTML to output?");
		Question q9 = new Question();
		q9.setLibrary(lib);
		q9.setDifficulty(1);
		q9.setValue("Which of the following are valid properties of @NgModule?");
		Question q10 = new Question();
		q10.setLibrary(lib);
		q10.setDifficulty(1);
		q10.setValue("Which of the following are NOT permitted within Angular 2 Templates: (Choose all that apply)");
		Question q11 = new Question();
		q11.setLibrary(lib);
		q11.setDifficulty(1);
		q11.setValue("Which @NgModule property specifies services that are used throughout the application? (Choose the best option)");
		Question q12 = new Question();
		q12.setLibrary(lib);
		q12.setDifficulty(1);
		q12.setValue("Which of the following metadata properties specifies the CSS selector to which the component will match?");
		Question q13 = new Question();
		q13.setLibrary(lib);
		q13.setDifficulty(1);
		q13.setValue("Which @NgModule property specifies services that are used throughout the application? (Choose the best option)");
		Question q14 = new Question();
		q14.setLibrary(lib);
		q14.setDifficulty(1);
		q14.setValue("Which of the following snippets correctly identifies a class as a service that you want injected in another class? (Choose the best option)");
		Question q15 = new Question();
		q15.setLibrary(lib);
		q15.setDifficulty(1);
		q15.setValue("True or False. ngClass is used to add/remove multiple styles using key/value pairs of CSS");
		Question q16 = new Question();
		q16.setLibrary(lib);
		q16.setDifficulty(1);
		q16.setValue("True or False. ngFor is used to toggle display of an element.");
		Question q17 = new Question();
		q17.setLibrary(lib);
		q17.setDifficulty(1);
		q17.setValue("True or False. @Directive is used for creating custom directives.");
		Question q18 = new Question();
		q18.setLibrary(lib);
		q18.setDifficulty(1);
		q18.setValue("True or False. @Component is a special form of the @Directive decorator.");
		Question q19 = new Question();
		q19.setLibrary(lib);
		q19.setDifficulty(1);
		q19.setValue("Which of the following are the three types of directives in Angular 2? (Choose all that apply)");
		Question q20 = new Question();
		q20.setLibrary(lib);
		q20.setDifficulty(1);
		q20.setValue("True or False. Property-binding and interpolation can be used to set an element's property for string values.");
		Question q21 = new Question();
		q21.setLibrary(lib);
		q21.setDifficulty(1);
		q21.setValue("Metadata is: (Choose the best option to complete the sentence).");
		Question q22 = new Question();
		q22.setLibrary(lib);
		q22.setDifficulty(1);
		q22.setValue("Which of the following decorators is the one used to specify metadata for the root module?");
		Question q23 = new Question();
		q23.setLibrary(lib);
		q23.setDifficulty(1);
		q23.setValue("Which module defines functionality for running your application in a web browser? (Choose the best option)");
		Question q24 = new Question();
		q24.setLibrary(lib);
		q24.setDifficulty(1);
		q24.setValue("True or False. All applications have at least one module.");
		Question q25 = new Question();
		q25.setLibrary(lib);
		q25.setDifficulty(1);
		q25.setValue("Which of the following snippets correctly uses event-binding according to Angular 2 syntax:");
		Question q26 = new Question();
		q26.setLibrary(lib);
		q26.setDifficulty(1);
		q26.setValue("True or False. The following is an example of event-binding syntax:");
		Question q27 = new Question();
		q27.setLibrary(lib);
		q27.setDifficulty(1);
		q27.setValue("True or False. Event-binding associates DOM events to component functions.");
		Question q28 = new Question();
		q28.setLibrary(lib);
		q28.setDifficulty(1);
		q28.setValue("Which of the following correctly uses property binding:");
		Question q29 = new Question();
		q29.setLibrary(lib);
		q29.setDifficulty(1);
		q29.setValue("True or False. Angular 2 supports TypeScript.");
		Question q30 = new Question();
		q30.setLibrary(lib);
		q30.setDifficulty(1);
		q30.setValue("What type of framework is Angular2?");
		Question q31 = new Question();
		q31.setLibrary(lib);
		q31.setDifficulty(1);
		q31.setValue("True or False. The AppComponent is typically the name for an Angular 2 application's root component.");
		Question q32 = new Question();
		q32.setLibrary(lib);
		q32.setDifficulty(1);
		q32.setValue("Which of the following files is typically used to link your application's components?");
		Question q33 = new Question();
		q33.setLibrary(lib);
		q33.setDifficulty(1);
		q33.setValue("Data-binding is: (Choose the best option to complete this sentence)");
		
		s.save(q1);
		s.save(q2);
		s.save(q3);
		s.save(q4);
		s.save(q5);
		s.save(q6);
		s.save(q7);
		s.save(q8);
		s.save(q9);
		s.save(q10);
		s.save(q11);
		s.save(q12);
		s.save(q13);
		s.save(q14);
		s.save(q15);
		s.save(q16);
		s.save(q17);
		s.save(q18);
		s.save(q19);
		s.save(q20);
		s.save(q21);
		s.save(q22);
		s.save(q23);
		s.save(q24);
		s.save(q25);
		s.save(q26);
		s.save(q27);
		s.save(q28);
		s.save(q29);
		s.save(q30);
		s.save(q31);
		s.save(q32);
		s.save(q33);
		
		Answer a1 = new Answer();
		a1.setQuestion(q1);
		a1.setCorrect(true);
		a1.setValue("Yes");
		s.save(a1);
		tx.commit();
		
		s.close();
		System.out.println(s.isOpen());
		HibernateUtil.closeSessionFactory();

	}

}
